### ISSUE TITLE
The generator doesn't add imports for names from other packages.

### ISSUE THREAD

**Issue by gordonklaus** [alecthomas/go-rpcgen#1]
For example, for

``` go
import "github.com/m4rw3r/uuid"
type X interface {
    F(id uuid.UUID) (err error)
}
```

the generated RPC stubs do not include the import of "github.com/m4rw3r/uuid".

**Comment by gordonklaus** [comment]
I'm using the `-imports` flag as a workaround, but it would be nice if this were automatic.

**Comment by alecthomas** [comment]
go-rpcgen does call goimports on the output to resolve imports, so this should work (and does for me). That said, it would be useful to be able to directly resolve imports, I agree.

**Comment by gordonklaus** [comment]
Apparently I don't have goimports installed :)  Thanks for the quick fix.
